(chore) Catch exceptions and log when both school type ID and organisation category ID are nil
```
2019-01-25 13:37:21.204,"F, [2019-01-25T13:37:21.204235 #10] FATAL -- : [c9dc6765-9cb2-46d0-bbb0-20042438bc33] NoMethodError (undefined method `non_profit?' for nil:NilClass):"
2019-01-25 13:37:21.204,"F, [2019-01-25T13:37:21.204337 #10] FATAL -- : [c9dc6765-9cb2-46d0-bbb0-20042438bc33] app/models/login/dfe_login.rb:49:in `rescue in non_profit?'"
```

When both school type ID and organisation category ID are nil, catch the exceptions and log the user details for future debug